services:
 db:
  image: postgis/postgis:17-3.5
  environment:
    POSTGRES_DB: ${DATABASE_NAME}
    POSTGRES_USER: ${DATABASE_USERNAME}
    POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
  container_name: postgis-docker
  networks:
    - django_traffic_network
  volumes:
    - postgres_data:/var/lib/postgresql/data
  env_file:
    - .env
 
 django-web:
  build: .
  container_name: django-docker
  networks:
    - django_traffic_network
  ports:
    - "8000:8000"
  volumes:
    - ./:/app 
  depends_on:
    - db
  environment:
    DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
    DEBUG: ${DEBUG}
    DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
    DATABASE_NAME: ${DATABASE_NAME}
    DATABASE_USERNAME: ${DATABASE_USERNAME}
    DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    DATABASE_HOST: ${DATABASE_HOST}
    DATABASE_PORT: ${DATABASE_PORT}
  env_file:
    - .env

volumes:
  postgres_data:

networks:
  django_traffic_network:
    name: django_traffic_network
    driver: bridge
