# Generated by Django 5.2.1 on 2025-05-20 23:21

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoadSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinate', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
                ('road_length', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SpeedReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speed', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('road_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speed_readings', to='traffic_monitor.roadsegment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
