# Generated by Django 5.2.1 on 2025-05-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("traffic_monitor", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrafficClassification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("LOW", "low"),
                            ("MEDIUM", "medium"),
                            ("HIGH", "high"),
                        ],
                        default="LOW",
                        max_length=25,
                        unique=True,
                    ),
                ),
                ("min_speed", models.FloatField(blank=True, null=True)),
                ("max_speed", models.FloatField(blank=True, null=True)),
            ],
            options={
                "ordering": ["min_speed"],
            },
        ),
    ]
