# Generated by Django 5.2.1 on 2025-05-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic_monitor', '0005_car_created_at_alter_trafficrecord_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficrecord',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
